pipeline {

    agent any
 
    environment {

        TEAMS_WEBHOOK_URL = 'https://imaginxavr.webhook.office.com/webhookb2/2d47e3e4-7bde-4804-9f1c-07cdc6126f5c@713a5df4-ce37-4131-8bc8-8f2c3415624f/IncomingWebhook/871b1a786fb84b408de72a7954932677/9296219f-afc4-4e8b-9a5c-ad73eb12cb2b/V2uL5xrIWZKlvyE2L9vmA7uzPmmBX2y81OZ7SjVZMHzys1%27

        TEST_URL = 'https://buildifyintech.com'

    }
 
    stages {
 
        stage('Install Dependencies') {

            steps {

                dir('D:/playwright-tests') {

                    bat 'npm ci || npm install'

                    bat 'npx playwright install'

                }

            }

        }
 
        stage('Run Tests') {

            steps {

                script {

                    try {

                        dir('D:/playwright-tests') {

                            bat 'npx playwright test'

                        }

                        currentBuild.result = 'SUCCESS'

                    } catch (e) {

                        currentBuild.result = 'FAILURE'

                        throw e

                    }

                }

            }

        }

    }
 
    post {

    always {

        script {
 
            // Read tested URL from file generated by Playwright test

            def testedUrl = readFile "D:/playwright-tests/tested_url.txt"
 
            def status = currentBuild.result

            def buildNumber = currentBuild.number   // ← Add Build Number

            def color = (status == 'SUCCESS') ? '00FF00' : 'FF0000'
 
            // Dynamic message based on result

            def messageTitle = (status == 'SUCCESS')

                ? "ImaginX Website: Loading smoothly with all basic content."

                : "ImaginX Website: Having issue with webpage."
 
            def json = """

            {

              "@type": "MessageCard",

              "@context": "http://schema.org/extensions",

              "themeColor": "${color}",

              "summary": "Playwright Test Result",

              "sections": [{

                "activityTitle": "${messageTitle}",

                "facts": [

                  { "name": "Status", "value": "${status}" },

                  { "name": "Build Number", "value": "${buildNumber}" },

                  { "name": "Tested URL", "value": "${testedUrl}" }

                ],

                "markdown": true

              }]

            }

            """
 
            writeFile file: 'message.json', text: json
 
            bat """

                curl -H "Content-Type: application/json" ^

                     -d @message.json ^

                     "${TEAMS_WEBHOOK_URL}"

            """

        }

    }

}
 
 
}

 
